### ISSUE TITLE
Gameplay report for 27th

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [agaped/OX#16]
Game welcomes me - nice. Game gives some info if I answer wrongly, nice. Game asks if I want to play again - nice. With spelling error (dou you want) and it doesn't respect my answer (n -> ok, we play again!). Something is wrong with win seq length and with announcing a winner - it comes few turn later for some reason? Minimalistic board, but that's ok. First time entering coordinates there's no info how it should be done. I expected 1 1 to be middle, but it was a first field. Expect follow-ups and see comment for session log.

**Comment by LIttleAncientForestKami** [comment]
Welcome to XO game!!!
Some setup at the beggining...

Provide board dimension y-vertical, x-horizontal: 
1 2
Provide length of combination to win: 
3
Impossible combination!!
Provide length of combination to win: 
1
Who shall start, X or O?
O

++
 
Player O, make your move
1
Wrong input! Provide move in a form: x y

++
 
Player O, make your move
1 2

+O
 
Player X, make your move
2 2
Wrong input! Loosing turn....


+O
 
Player O, make your move
1 1

OO
 
Draw!!!

Welcome to XO game!!!
Some setup at the beggining...

Provide board dimension y-vertical, x-horizontal: 
3 3
Provide length of combination to win: 
3
Who shall start, X or O?
X

+++
+++
+++
 
Player X, make your move
1 1 

X++
+++
+++
 
Player O, make your move
1 2

XO+
+++
+++
 
Player X, make your move
2 2

XO+
+X+
+++
 
Player O, make your move
1 3

XOO
+X+
+++
 
Player X, make your move
3 3

XOO
+X+
++X
 
Player O, make your move
1 1
Move not possible! Loosing turn....


XOO
+X+
++X
 
Player X, make your move
2 1

XOO
XX+
++X
 
Player O, make your move
3 1
Winner is X
Dou you want to play again? y/n
n

Thanks for playing!
Statistics:....
Welcome to XO game!!!
Some setup at the beggining...

Provide board dimension y-vertical, x-horizontal: 
^C%

**Comment by agaped** [comment]
corrected, thanks!
